<a href="https://colab.research.google.com/github/joshirdzdel-svg/estadisticainferencial2026A/blob/main/problemario_unidad_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PROBLEMARIO_UNIDAD_4

1° comparacion de cuatro métodos de ensamble.
Un equipo de mejora, investiga cuatro métodos de ensamble A, B, C, D sobre el tiempo de ensamble en minutos. En primera instancia, la primera estrategia experimental, es aplicar cuatro veces los cuatro métodos de ensamble en orden completamente aletorio y se obtienen lo siguiente:
|método de ensamble|A |B |C |D |
|------------------|--|--|--|- |
|                  |6 |7 |11|10|
|                  |8|9|16|12|
|                  |7|10|11|11|
|                  |8|8|13|9|

In [7]:

import pandas as pd
link_csv = "https://raw.githubusercontent.com/joshirdzdel-svg/estadisticainferencial2026A/refs/heads/main/Unidad_4/problemario_01.csv"
df = pd.read_csv(link_csv)
df

   metodo  tiempo
0       A       6
1       A       8
2       A       7
3       A       8
4       B       7
5       B       9
6       B      10
7       B       8
8       C      11
9       C      16
10      C      11
11      C      13
12      D      10
13      D      12
14      D      11
15      D       9

In [8]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

modelo = ols("tiempo ~ C(metodo)", data=df).fit()
tabla_anova = sm.stats.anova_lm(modelo, typ=2)
tabla_anova.round(4)

           sum_sq    df       F  PR(>F)
C(metodo)    69.5   3.0  9.4237  0.0018
Residual     29.5  12.0     NaN     NaN